#
# Copyright (c): it@M - Dienstleister für Informations- und Telekommunikationstechnik
# der Landeshauptstadt München, 2024
#

FROM registry.access.redhat.com/ubi9/openjdk-17:latest

COPY target/*.jar /deployments/spring-boot-application.jar