#
# Copyright (c): it@M - Dienstleister für Informations- und Telekommunikationstechnik
# der Landeshauptstadt München, 2024
#

spring:
  # Spring JPA
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ppdb

  h2.console.enabled: true
  jpa:
    database: H2
