spring:
  # spring cloud gateway config
  cloud:
    gateway:
      routes:
        - id: backend
          uri: ${app.gateway.routing.backend.uri}
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<urlsegments>.*), /api/$\{urlsegments}
            - RemoveResponseHeader=WWW-Authenticate