// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddPersonDialog: typeof import('./src/components/AddPersonDialog.vue')['default']
    DatentransferTable: typeof import('./src/components/DatentransferTable.vue')['default']
    DatetimeInput: typeof import('./src/components/common/DatetimeInput.vue')['default']
    ManageSchnittstelleDialog: typeof import('./src/components/ManageSchnittstelleDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheSnackbar: typeof import('./src/components/TheSnackbar.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDataTable: typeof import('vuetify/lib')['VDataTable']
    VDatePicker: typeof import('vuetify/lib')['VDatePicker']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFadeTransition: typeof import('vuetify/lib')['VFadeTransition']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VLazy: typeof import('vuetify/lib')['VLazy']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VMain: typeof import('vuetify/lib')['VMain']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VRow: typeof import('vuetify/lib')['VRow']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
    YesNoDialog: typeof import('./src/components/common/YesNoDialog.vue')['default']
  }
}
