name: Frontend compliance check and build test

on:
  push:
    branches-ignore:
      - 'sprint'
      - 'main'
    paths:
      - 'mobidam-sst-management-frontend/**'
      - '.github/workflows/**'
  pull_request:
    types: [ opened, reopened ]

jobs:
#  compliance:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Advance Security Policy as Code
#        uses: advanced-security/policy-as-code@v2.7.3
#        with:
#          policy: it-at-m/policy-as-code
#          policy-path: default.yaml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          argvs: "--disable-dependabot --disable-secret-scanning --disable-code-scanning --display"

  build-maven:
    needs: compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build with Maven
        run: mvn --update-snapshots -f mobidam-sst-management-frontend/pom.xml verify