name: Release artefacts

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Services release version'
        type: string
        required: true

jobs:

  backend-release:
    uses: ./.github/workflows/workflow-release-backend.yml
    with:
      version: ${{ github.event.inputs.release-version }}
    secrets: inherit

  frontend-release:
    uses: ./.github/workflows/workflow-release-backend.yml
    with:
      version: ${{ github.event.inputs.release-version }}
    secrets: inherit

  github-release:
    needs: [backend-release, frontend-release]
    name: Create github release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.release-version }}',
              sha: context.sha
            })

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release-version }}
          release_name: Release ${{ github.event.inputs.release-version }}
          draft: false
          prerelease: false