name: Build and publish backend to test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which backend version should be deployed to production?'
        required: true
        default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout to specific version
        uses: actions/checkout@v4
        with: { ref:  refs/tags/backend-${{ github.event.inputs.version }} }

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build with Maven
        run: mvn -B verify -f mobidam-sst-management-backend/pom.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./mobidam-sst-management-backend
          push: true
          tags: itatm/mobidam:mobidam-sst-management-backend-prod
