name: Build and release to demo

on:
  workflow_dispatch: # execute manually
  schedule:
    - cron: '0 12 * * 2' # execute automatically every Tuesday at 12:00pm

jobs:
  backend-build-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get number of Tuesday on a Tuesday
        if: github.event_name != 'workflow_dispatch' # the following constraint is only applied if the job was triggered automatically
        id: number-of-tuesday
        run: >- # ((day_of_month-1)/7)+1 works only if the job is only triggered on tuesdays, https://stackoverflow.com/a/75975946
          printf >> "$GITHUB_OUTPUT"
          "VALUE=%s"
          "$((($(date +%d)-1)/7+1))" # (3)

      - name: Check if job should be run # the automatically triggered actions should only be executed every 3 weeks
        if: github.event_name != 'workflow_dispatch' && steps.number-of-tuesday.outputs.VALUE != 3
        run: | # canceling the job if the conditions weren't met, https://stackoverflow.com/a/75809743
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git checkout to main branch # the workflow is triggered in the default branch, which doesn't have to be MAIN
        uses: actions/checkout@v4
        with: { ref: main } # this also serves as a safeguard for workflows triggered manually

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --update-snapshots -f mobidam-sst-management-backend/pom.xml verify

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./mobidam-sst-management-backend
          push: true
          tags: itatm/mobidam-sst-management-backend:demo

  frontend-build-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get number of Tuesday on a Tuesday
        if: github.event_name != 'workflow_dispatch' # the following constraint is only applied if the job was triggered automatically
        id: number-of-tuesday
        run: >- # ((day_of_month-1)/7)+1 works only if the job is only triggered on tuesdays, https://stackoverflow.com/a/75975946
          printf >> "$GITHUB_OUTPUT"
          "VALUE=%s"
          "$((($(date +%d)-1)/7+1))" # (3)

      - name: Check if job should be run # the automatically triggered actions should only be executed every 3 weeks
        if: github.event_name != 'workflow_dispatch' && steps.number-of-tuesday.outputs.VALUE != 3
        run: | # canceling the job if the conditions weren't met, https://stackoverflow.com/a/75809743
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git checkout to main branch # the workflow is triggered in the default branch, which doesn't have to be MAIN
        uses: actions/checkout@v4
        with: { ref: main } # this also serves as a safeguard for workflows triggered manually

      - name: Fail if branch is not main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
          exit 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --update-snapshots -f mobidam-sst-management-frontend/pom.xml verify

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./mobidam-sst-management-frontend
          push: true
          tags: itatm/mobidam-sst-management-frontend:demo