name: Release docs

on: [workflow_dispatch]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: sprint
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: https://it-at-m.github.io/mobidam-sst-management/