name: Build integration release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to release from ?"
        required: true
        default: "main"
      release-version:
        description: "Release version ?"
        required: true
      release-tag:
        description: "Release tag ?"
        required: true
      development-version:
        description: "Next Development version ?"
        required: true

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout to main branch # Releases are published on main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup git user
        uses: fregante/setup-git-user@v2

      - name: Set up JDK and OSSRH auth / GPG signing
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
          server-id: "central"
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.gpg_private_key }}
          gpg-passphrase: SIGN_KEY_PASS

      - name: Perform maven release
        run: >
          mvn --batch-mode --no-transfer-progress -Prelease release:prepare sign release:perform
          -DreleaseVersion=${{ github.event.inputs.release-version }} 
          -DdevelopmentVersion=${{ github.event.inputs.development-version }} 
          -Dtag=${{ github.event.inputs.release-tag }} 
          -Darguments="-DskipTests"
        env:
          SIGN_KEY_PASS: ${{ secrets.gpg_passphrase }}
          CENTRAL_USERNAME: ${{ secrets.sonatype_username }}
          CENTRAL_PASSWORD: ${{ secrets.sonatype_password }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release-tag }}
          draft: false
          prerelease: false
          generate_release_notes: false
