name: Build and release to demo

on:
  workflow_dispatch: # execute manually
  schedule:
    - cron: '0 12 * * 2' # execute automatically every Tuesday at 12:00pm

jobs:
  backend-build-and-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get number of Tuesday on a Tuesday
        run: |
          project_start_date=$(echo -n "2023-10-28 12:00")
          project_start_epoch_seconds=$(date -d "$project_start_date" +%s)
          time_passed=$($project_start_epoch_seconds-$(date +"%s"))
          echo "$time_passed"