name: Build frontend snapshot container

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which part of the version to increase (major, minor, patch)'
        required: true
        default: 'none'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- name: Git checkout to main branch # this serves as a safeguard for workflows triggered manually
      #  uses: actions/checkout@v4
      #  with: { ref: main }

      - name: Set Maven Project Version
        id: set-version
        run: |
          current_version=$(mvn help:evaluate -f mobidam-sst-management-frontend/pom.xml -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $current_version"
          if [ "${{ github.event.inputs.version }}" == "major" ]; then
            new_version=$(echo $current_version | awk -F. -v OFS=. '{$1=$1+1; $2=0; $3=0; print $0"-SNAPSHOT"}')
          elif [ "${{ github.event.inputs.version }}" == "minor" ]; then
            new_version=$(echo $current_version | awk -F. -v OFS=. '{$2=$2+1; $3=0; print $0"-SNAPSHOT"}')
          elif [ "${{ github.event.inputs.version }}" == "patch" ]; then
            new_version=$(echo $current_version | awk -F. -v OFS=. '{$3=$3+1; print $0"-SNAPSHOT"}')
          else
            new_version="$current_version"
          fi
          echo "New version: $new_version"
          mvn -B versions:set -DnewVersion=$new_version -f mobidam-sst-management-frontend/pom.xml
          if [ "${{ github.event.inputs.version }}" != "none" ]; then
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add mobidam-sst-management-frontend/pom.xml
            git commit -m "Bump frontend version to $new_version"
            git push
          fi
          echo "::set-output name=new_version::$new_version"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build with Maven
        run: mvn -B verify -f mobidam-sst-management-frontend/pom.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./mobidam-sst-management-frontend
          push: true
          tags: itatm/mobidam:mobidam-sst-management-frontend-${{ steps.set-version.outputs.new_version }},itatm/mobidam:mobidam-sst-management-frontend-prod
