name: Build and Deploy Vuepress
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: it-at-m/mobidam-sst-management
          TARGET_BRANCH: test/vuepress2
          BUILD_SCRIPT: cd docs && yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: https://it-at-m.github.io/mobidam-sst-management/