name: Frontend release

on:
  workflow_call:
    inputs:
      release-version:
        description: 'Services release version'
        type: string
        required: true

jobs:
  release:
    name: Create docker release
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: "maven"

      - name: Clean Maven Project Version
        id: set-version
        run: |
          current_version=$(mvn help:evaluate -f mobidam-sst-management-frontend/pom.xml -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $current_version"
          new_version=$(echo $current_version | sed 's/-SNAPSHOT//')
          echo "New version: $new_version"
          mvn -B versions:set -f mobidam-sst-management-frontend/pom.xml -DnewVersion=$new_version
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add mobidam-sst-management-frontend/pom.xml
          git commit -m "Bump frontend main version to $new_version"
          git push
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn -B verify -f mobidam-sst-management-frontend/pom.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push app
        uses: docker/build-push-action@v4
        with:
          context: ./mobidam-sst-management-frontend
          push: true
          tags: itatm/mobidam-sst-management-frontend:${{ steps.set-version.outputs.new_version }}, itatm/mobidam-sst-management-frontend:latest
